### ISSUE TITLE
Add images, videos and other elements in blogpost

### ISSUE THREAD

**Issue by meugster** [ChristopherDosin/Shopware-6-Blog-Plugin#10]
When writing blogposts, we need the flexibility to add media such as:

- images, galleries
- full-width images
- YouTube or Vimeo Videos
- Shopware Products
- possibilites to change the layout (e.g. bootstrap layout: rows, classes, padding, background)

One possibility could be the (buggy) Shopware editor. These element work quite well for writing blogposts even though the HTML output can be really bad.

**Comment by ChristopherDosin** [comment]
Currently, you can add an image from another website or image hoster. 
For example https://cloudinary.com/

Just copy & paste the image. The [simple Image tool ](https://github.com/editor-js/simple-image)is used here. 
However - We still need to fully integrate the whole Shopware Media Library if you want to use Media images from Shopware.

Regarding YouTube or Vimeo Videos:
Just copy & paste the URL to the editor and it will be pre-fetched.

Regarding the Shopware editor: We could add a plugin option to enable/disable the Shopware Text Editor.

Regarding Shopware Products: This will come in the future, yep. But i can't tell you when. It depends on our workload and when i find some free time to do so.

Please try to split your feature requests instead of writing them all into one ticket :)

**Comment by meugster** [comment]
Thanks, I'll try these options and split the feature requests (if still needed) into separate tickets (sorry 🙃).
