### ISSUE TITLE
Plugin Licensing

### ISSUE THREAD

**Issue by ShopwareTree** [ChristopherDosin/Shopware-6-Blog-Plugin#214]
Was there a recent change in pricing of the plugin in the shopware store?
https://store.shopware.com/en/sas6294283137222/blog-module.html

I've read multiple times that it was free in the store (also based on the downloads this would indicate it).

> The plugin is open source and you can find it on  https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin . Maintainer of the plugin is https://github.com/ChristopherDosin.

Opensource doesn't mean free to use, but according to the LICENSE file in this repository it is under MIT License:
https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/blob/master/LICENSE

After installing it via github sourcecode, shopware recognized it as unauthorized which it actually isn't.
Do I have to modify the source so shopware doesn't recognize it?

In the TOS of shopware this paragraph outlines this:
> 3.8.2.3.3. A contract for a software extension in a SHOPWARE Store shall be concluded upon installation of the software extension.

As far as my understanding goes of licensing, i licensed the plugin to myself (which is a valid use of MIT), which does not create a contract with shopware.

**Comment by ChristopherDosin** [comment]
We have to change the license within the GitHub repo, thanks for the hint.

And yes: The plugin was free - We wanted to keep it free for version, but we couldn't due to some store restrictions of the Shopware store.

We put a lot of work into version 2 and the on-going maintenance, that's why version 2 is paid. But also version 1 due to the store limitations of the Shopware store.

**Comment by ShopwareTree** [comment]
> We have to change the license within the GitHub repo, thanks for the hint.
> 
> And yes: The plugin was free - We wanted to keep it free for version, but we couldn't due to some store restrictions of the Shopware store.
> 
> We put a lot of work into version 2 and the on-going maintenance, that's why version 2 is paid. But also version 1 due to the store limitations of the Shopware store.

That's unfortunate, I guess it doesn't matter if it's open-source anymore then after version 2.0.8
it's imo too expensive.

**Comment by ChristopherDosin** [comment]
If you think a lunch per month is too expensive for the value and work, that's okay.
I will close this ticket then 👍

**Comment by webkp** [comment]
Same here as @ShopwareTree experienced:
> After installing it via github sourcecode, shopware recognized it as unauthorized which it actually isn't. Do I have to modify the source so shopware doesn't recognize it?

It is your decision whether you offer the plugin for free or not, but please change the license. Now you assume that you are installing a free plugin (I already checked if you can be sponsored via GitHub because I thought it was so cool) only to realize that it is a paid extension and you get warning mails from Shopware.

PS: Of course a lot of work has gone into the extension, but if you are starting out or have a small store or products with low prices, you have to think about whether you want to spend 360 - 470 EUR per year on a blog module. **Not because it doesn't have this value**, but because you first have to generate revenue with the store. And a blog module is usually not the only extension you might need, so it just adds up in the end.
